# -*- coding: utf-8 -*-
"""pytorch_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kgjBrGDEX_Zlgvkuvc9zMVEN5uzdjNNT

# Introduction to Tensors
"""

# Import all relevant libraries
# pytorch, pandas, numpy, matplotlib.pyplot

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

"""## Creating tensors

PyTorch tensors can be created using "torch.Tensor()"
"""

# Scalar
scalar = torch.tensor(7)
scalar

scalar.ndim

# Get tensor back as python int
scalar.item()

# Vector
vector = torch.tensor([7,7])
vector

vector.ndim

vector.shape

# MATRIX
MATRIX = torch.tensor([[7,8],
                       [6,7]])
MATRIX

MATRIX.ndim

MATRIX[0]

MATRIX[1]

MATRIX.shape

# TENSOR

TENSOR = torch.tensor([[[3,4,9],
                        [5,8,9],
                        [7,4,9]]])
TENSOR

TENSOR.ndim

TENSOR.shape

TENSOR[0]

TENSOR[0][0]

TENSOR[0][1]

TENSOR[0][2]

"""# Creating random tensors"""

# Create random tensor of size (3, 5) => 15 elements

3 * 5

random_tensor = torch.rand(3, 5)
random_tensor

random_tensor.ndim

random_tensor.shape

"""Creating a random tensor with similar shape to an image"""

# rand(height, with, number of color channels)

random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor

random_image_size_tensor.shape

random_image_size_tensor.ndim

"""Creating tensors with zeros and ones"""

# Create a tensorof all zeros
zeros = torch.zeros(size=(3,5))
print(zeros)

zeros * random_tensor

# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

# Check tensor datatype
ones.dtype

# Check tensor datatype
random_image_size_tensor.dtype

"""Creating a range of tensors and tensors-like"""

# Using torch.range()
# If you get a deprecated message, use torch.arange()
# Create tensor from 1 to 10
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

# Create tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

"""Tensor datatypes

**Note:** Below are the 3 main issues you'll commonly face in PyTorch and deep learning:
1. Tensors not in right **datatype**
2. Tensors not in right **shape**
1. Tensors not on right **device**

Read more on precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)
"""

# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

float_32_tensor.dtype

# Change tensor datatype from Float 32 to Float 16
float_16_tensor = torch.tensor([3.0, 7.0, 9.0],
                               dtype=torch.float16, # Tensor datatype e.g. float32 or float16
                               device=None, # What device to run tensor on. Can be changed to "cpu" or "cuda"
                               requires_grad=False) # Whether or not to track gradients with this tensor's operations
float_16_tensor

float_16_tensor.dtype

# Convert float32 tensor to float16 tensor
another_float_16_tensor = float_32_tensor.type(torch.float16)
another_float_16_tensor

# Multiply tensors of 2 different datatypes (float16 & float32)
# Returns default float32 tensor
multiplication_result = float_32_tensor * float_16_tensor
multiplication_result

multiplication_result.dtype

"""Getting information from tensors

1. To get tensor datatype, we use `tensor.dtype`
2. To get tensor shape, there's 2 ways. Using an attribute, we use `tensor.shape`. Using a function, we use `tensor.size()`
3. To get tensor device, we use `tensor.device`
"""

# Create random tensor
some_random_tensor = torch.rand(3,4)
some_random_tensor

# Find out some details about tensor
print(f"Datatype of tensor: {some_random_tensor.dtype}")
print(f"Shape of tensor using attribute: {some_random_tensor.shape}")
print(f"Shape of tensor using function: {some_random_tensor.size()}")
print(f"Device of tensor: {some_random_tensor.device}")

"""Manipulating tensors / Tensor Operations

# Tensor operations include the following:

**1.** Addition

**2.** Subtraction

**3.** Multiplication (element-wise)

**4.** Division

**5.** Matrix multiplication (dot product)
"""

# Addition
# Create a tensor and add 100 to it
tensor = torch.tensor([1,2,4])
tensor + 100

# For addition, we can also use a function `torch.add`
tensor_add = torch.tensor([4,5,6])
torch.add(tensor_add, 10)

# Subtraction
# Create a tensor and subtract 100 from it
tensor = torch.tensor([1,2,4])
tensor - 100

# Multiplication
# Create a tensor and multiply it by 100
tensor = torch.tensor([1,2,4])
tensor * 100

# For multiplication, we can also use a function `torch.mul`
tensor_mul = torch.tensor([4,5,6])
torch.mul(tensor_mul, 10)

# Division
# Create a tensor and multiply it by 100
tensor = torch.tensor([1,2,4])
tensor * 100

"""Matrix multiplication

There's 2 main ways of multiplying matrices
1. Element-wise multiplication
2. Matrix multiplication (dot product)

Read more here: https://www.mathsisfun.com/algebra/matrix-multiplying.html
"""

# Element wise multiplication
print (tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

# Matrix multiplication (Dot Product)
torch.matmul(tensor, tensor)

# Matrix multiplication by hand
{1*1 + 2*2 + 4*4}

"""Testing the speed of using matmul vs. multiplication by hand"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# value = 0
# for i in range(len(tensor)):
#   value += tensor[i] * tensor[i]
# print(value)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# torch.matmul(tensor, tensor)

"""There are 2 main rules we must satisfy when performing matrix multiplication:

1. The **inner dimensions** must match


*   (3,**2**) @ (**3**,2) won't work
*   (2,**3**) @ (**3**,2) will work
*   (3,**2**) @ (**2**,3) will work

The above is what's called **"shape errors"**

2. The resulting matrix has the shape of the **outer dimensions**
*   (3,**2**) @ (**2**,3) results into (3,3)
"""

### Example error for inner dimensions mismatch
torch.matmul(torch.rand(3,2), torch.rand(3,2))

### Example of how to fix the above error simply by making sure inner dimensions match
torch.matmul(torch.rand(3,2), torch.rand(2,3))

"""How to deal with **Shape Errors**"""

# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

tensor_A.shape, tensor_B.shape

"""# To fix our tensor issues, we can manipulate the shape of one of the tensors using a **transpose**

**A transpose** swicthes the axes or dimensions of a given tensor
"""

# Original tensor
tensor_B, tensor_B.shape

# Transposed tensor
tensor_B.T, tensor_B.T.shape

## The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")

output = torch.mm(tensor_A, tensor_B.T)

print(output)
print(f"\nOutput shape: {output.shape}")

"""# Tensor Aggregation

Finding the min, max, mean, sum etc of tensors

"""

